language: node_js
node_js:
  - "10"
cache:
  - functions/node_modules
branches:
  only:
  - master
before_script:
  - npm install -g firebase-tools
  - cd functions
  - npm install
script:
  - firebase use default --token $FIREBASE_DEPLOY_KEY
  - firebase config:set GCLOUD_PROJECT="$FIREBASE_PROJECT_ID" 
  - firebase deploy -m "Travis build $TRAVIS_BUILD_NUMBER" --non-interactive --force --token $FIREBASE_DEPLOY_KEY
